### ISSUE TITLE
v1alpha1 not working

### ISSUE THREAD

**Issue by gjvanhalem** [in-toto/totoify-grafeas#1]
Hi there, we want to use in-toto with grafeas to prove complance in a CI/CD pipeline. So we started out with this project (after testing out in-toto itself). But I am having trouble to get it working as it is. the v1alpha1 version does not work at all for me.
I tried it with v1beta1 from grafeas but the api seems to have changed quite a lot. the operations method is not available anymore. And the note model seems to have changed. 
Can you please point me in the right direction? We are willing to invest time to make it work.

Thanks
Gert Jan

**Comment by SantiagoTorres** [comment]
Hi Gert!

yes, I think we'd have to update for the beta or the most recently released 1.0 version of Grafeas. We've been waiting for more interest from the community to focus efforts here again. We'll ping you with updates about this as soon as we have things going. 

You're also more than welcome to take a first stab at this if you're interested :)

**Comment by gjvanhalem** [comment]
Thanks! in the meantime I got it working with v1alhpa1. That made me understand better how it works.
We are looking into using this in a large bank. Next week we want to decide if this is the best way to go, if so, we will definitely start working on bringing it to v1
